- name: Casey Philip Playbook
  hosts: all
  tasks:
    - name: Print A Message
      debug:
        msg: "Hello AWX! This is Casey and Philip!"
    - name: Run the command if the specified file does not exist.
      command: ls -al
    - name: Deploy Hello World Application
      copy:
        src: ./hello_world_app/hello.sh
        dest: /usr/local/hello.sh
        owner: root
        group: root
        mode: 0755
    - name: Run the command if the specified file does not exist.
      command: /usr/local/hello.sh        